spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news_service?&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
service:
  url:
    client: http://localhost:3000